### PR TITLE
Add nbstripout pre-commit hook

### PR DESCRIPTION
**Pull request by SimonHeybrock**
- Copy config from scipp repo
- Add `nbstripout`. This is slightly different from `nb-clean` used in CI, but has the advantage of being usable as a pre-commit hook. If it works, my plan is to also use this in CI.

### CODE REVIEW

**Comment by jl-wynen** [comment]
I assume, you tested the hook?

**Comment by SimonHeybrock** [comment]
Yes. The only thing it did not strip was and empty list of tags. I don't know if nb-clean is doing that though?

**Comment by jl-wynen** [comment]
Does it matter? Can those be introduced accidentally?

What about empty cells?

**Comment by SimonHeybrock** [comment]
Empty cells are removed by the `'--strip-empty-cells'` option.

Empty list of tags appears when you collapse an markdown section. The collapse information gets stripped, but empty list of tags remains.

**Review by jl-wynen — APPROVED** [review]
Ok, let's try it

**Pull request merged**
